# Generated by Django 5.2.8 on 2026-07-09 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizattempt",
            options={"ordering": ["-started_at"]},
        ),
    ]
