services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000/api
    container_name: quiz_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    working_dir: /app
  db:
    image: postgres:15
    container_name: quiz_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-quiz_db}
      POSTGRES_USER: ${DB_USER:-quiz_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-quiz_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
